### ISSUE TITLE
Teams Outlook Addin wird nicht installiert

### ISSUE THREAD

**Issue by haselnuss1971** [Koetzing/Powershell-Scripts#1]
Danke für das super Script! 

(Server 2022)
         .Version
        - 1.0 creation 03/30/24
        - 1.1 Teams command line issues fixed

Ich habe jedoch das Problem, dass das Outlook Addin nicht installiert wird.
Der Ordner bleibt mit dem Logfile leer.
Ich starte das Script unattended auf dem Server mit Admin Rechten.
Teams ist installiert, auch die Regkeys werden alles gesetzt, nur das Addin will nicht.
Hier das Logfile:

=== Verbose logging started: 02.06.2024  14:58:39  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\SysWOW64\msiexec.exe ===
MSI (c) (10:FC) [14:58:39:591]: Resetting cached policy values
MSI (c) (10:FC) [14:58:39:591]: Machine policy value 'Debug' is 0
MSI (c) (10:FC) [14:58:39:591]: ******* RunEngine:
           ******* Product: \MicrosoftTeamsMeetingAddinInstaller.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (10:FC) [14:58:39:591]: Client-side and UI is none or basic: Running entire install on the server.
MSI (c) (10:FC) [14:58:39:591]: Grabbed execution mutex.
MSI (c) (10:FC) [14:58:39:591]: Cloaking enabled.
MSI (c) (10:FC) [14:58:39:591]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (10:FC) [14:58:39:591]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (B4:88) [14:58:39:607]: Running installation inside multi-package transaction C:\MicrosoftTeamsMeetingAddinInstaller.msi
MSI (s) (B4:88) [14:58:39:607]: Grabbed execution mutex.
MSI (s) (B4:CC) [14:58:39:607]: Resetting cached policy values
MSI (s) (B4:CC) [14:58:39:607]: Machine policy value 'Debug' is 0
MSI (s) (B4:CC) [14:58:39:607]: ******* RunEngine:
           ******* Product: C:\MicrosoftTeamsMeetingAddinInstaller.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (s) (B4:CC) [14:58:39:607]: Note: 1: 2203 2: C:\MicrosoftTeamsMeetingAddinInstaller.msi 3: -2147287038 
MSI (s) (B4:CC) [14:58:39:607]: MainEngineThread is returning 2
MSI (s) (B4:88) [14:58:39:607]: User policy value 'DisableRollback' is 0
MSI (s) (B4:88) [14:58:39:607]: Machine policy value 'DisableRollback' is 0
MSI (s) (B4:88) [14:58:39:607]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (B4:88) [14:58:39:607]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (B4:88) [14:58:39:607]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (B4:88) [14:58:39:607]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (10:FC) [14:58:39:622]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (10:FC) [14:58:39:622]: MainEngineThread is returning 2
=== Verbose logging stopped: 02.06.2024  14:58:39 ===

Vielen Dank für Ihre Hilfe.
Viele Grüsse Jürgen Meier

**Comment by haselnuss1971** [comment]
Als Ergänzung, das Addi wird installiert, wenn ich den Abschnitt von Hand ausführe. (Also ebenfalls als Admin) aber nicht durch einen Aufruf des ps1 durch eine exe-Datei unattended.

**Comment by haselnuss1971** [comment]
Der Pfad: C:\MicrosoftTeamsMeetingAddinInstaller.msi im Logfile ist wohl nicht richtig.

**Comment by Koetzing** [comment]
Hm, ich denke, es ist  ein Timing-Problem und hatte dafür auch schon einen Timer, aber der scheint bei den Änderungen verloren gegangen zu sein oder ich habe ihn final nicht übernommen. Muss ich die Tage noch einpflegen.

**Comment by haselnuss1971** [comment]
Hallo Thomas,
vielen Dnak für Deine schnelle Antwort.

Also ich gehe so vor:
Ich habe ein NSIS Script (Kompilliert in eine exe), welches alles Files in C:\temp kopiert, auch das Powershell script von Dir.
Wenn alles kopiert wurde, wird Dein Script mit einem Installationsbenutzer (Dom.-Admin) aufgerufen.
Der Angemeldete Benutzer ist aber nicht der Installationsbenutzer, aber dieser ist auch Dom.-Admin.
Evtl. liegt es daran?

Dein neues Script mit dem BIts Download Aufruf geht bei mir gar nicht, das kann nur vom angemeldeten Benutzer ausgeführt werden.

Nochmals vielen Dank!

**Comment by Koetzing** [comment]
Ich habe das Timeout gefunden, war aber in meinem Teams-Update Skript, das ich bisher nicht veröffentlicht habe. Habe jetzt alle Teams-Skripts um das Timeout ergänzt.
Bei Teams kann es nach der Installation ca. 30 Sekunden dauern, bevor es komplett im System registriert wird. Wenn das Skript einfach weiterläuft, dann kann der Pfad nicht ausgelesen werden und damit wird das Plug-in nicht installiert.

**Comment by Koetzing** [comment]
> Dein neues Script mit dem BIts Download Aufruf geht bei mir gar nicht, das kann nur vom 
>angemeldeten Benutzer ausgeführt werden.
Remote habe ich so noch gar nicht getestet und müsste ich erst prüfen, woran es liegen könnte, ggf. an der Admin-Abfrage im PoSh.

**Comment by haselnuss1971** [comment]
Super, habe gerade einen Server ins Deploymend geschickt mit dem Timeout.
Leider dauert es ca. 3 Stunden bis alles installiert ist, und ich nachschauen kann, melde mich aber umgehend mit dem Ergebnis.

**Comment by Koetzing** [comment]
Der Timeout ist aber nur 30 Sekunden.

**Comment by haselnuss1971** [comment]
Guten Morgen, den Timeout habe ich af 180 Sekunden gesetzt, ist aber leider das selbe Ergebnis..
Das Addin fehlt, Ordner mit Logfile ist vorhanden.

**Comment by Koetzing** [comment]
Das müsste man sich genauer ansehen, denn es bedeutet, dass Teams nicht oder zumindest während der Installation nicht als AppX-Paket registriert wurde. Es hängt ggf. mit der Remote-Installation zusammen. So gibt es für mich nur zwei Möglichkeiten:
1. Outlook-Add-in aus dem AppX-Paket extrahieren und dann aus dem Install-Pfad installieren (müsste im Skript angepasst werden).
2. Es wird nicht die AppX Eigenschaften abgefragt, sondern direkt über die Verzeichnisse, was auch erst im Skript angepasst werden müsste.

Das Skript wurde aber schon vielfach verwendet und du bist bisher der Einzige mit dem Problem.

**Comment by haselnuss1971** [comment]
Hallo Thomas, das ist kein Problem, ich habe 6 Server, da kann ich Dein Script auch von Hand ausführen.
Evtl. ergibt sich ja die etwas, die Zeit läuft.
Vielen Dank für das Script sowie Deine Hilfe!
Ich bin ein Fan von Dir!
